### PR TITLE
Downsize images/SOMAExperiment.png

### PR DESCRIPTION
**Pull request by johnkerl**
Follow-on from #106:
https://github.com/single-cell-data/SOMA/pull/106#pullrequestreview-1281652257

### CODE REVIEW

**Review by atolopko-czi — APPROVED** [review]
The downscaling didn't quite fix it. I think we just need to (eventually) recreate it "from source". Not sure if it's worth merging this, but I'll approve it and leave the decision to you. Thanks for giving it a shot!

**Comment by johnkerl** [comment]
@atolopko-czi sorry, what's the "it" that we didn't fix -- ??

**Comment by johnkerl** [comment]
(I did recreate the image -- got the doc link from @bkmartinjr and screenshotted it, then downsized that screenshot to match the previous dimensions. That's all.)

**Comment by atolopko-czi** [comment]
> @atolopko-czi sorry, what's the "it" that we didn't fix -- ??

the image still looks fuzzy. :) this is not important enough to worry about any further!

**Pull request merged**
