### PR TITLE
Remove obs_ms and var_ms from images/SOMAExperiment.png

### LINKED ISSUE #63: Spec should not contain obs_ms/var_ms
These were deleted, but not removed from the diagram/image.  Needs to be consistent, by cleaning up the image/diagram.

### PR DESCRIPTION
**Pull request by johnkerl**
Fixes #63

See attached image -- `obs_ms` and `var_ms` are no longer in the verbal spec.

### CODE REVIEW

**Review by bkmartinjr — CHANGES_REQUESTED** [review]
the types documented in the X layer are wrong - per the spec, X layers can be Dense or Sparse.

See #45.

**Comment by johnkerl** [comment]
@bkmartinjr please share the original document you used to create this image.

I was photo-editing, which is non-optimal.

**Comment by bkmartinjr** [comment]
> @bkmartinjr please share the original document you used to create this image.

will do offline as it is a gdoc thingy.  It was previously shared with @aaronwolen

we may want to consider some other master - but I don't have a good suggestion for an alternative

**Comment by johnkerl** [comment]
@maniarathi ping

**Review by atolopko-czi — APPROVED** [review]
The desired sections have been removed. But honestly, the larger resolution image is being downscaled in the README.md and is no longer displayed at its native resolution. While a minor concern, this is an important image in the spec, and should look better, IMO. Can we show at 1:1 resolution? Too big?

I'll approve as is, but suggest we create a new issue to recreate the image from its original image editing app  at the desired resolution (understanding we need to figure out where that is).

Github visual diff didn't work, so I diffed between commits https://github.com/single-cell-data/SOMA/blob/2f090afd1b788f115407b95fed54a3de756e07fb/images/SOMAExperiment.png and https://github.com/single-cell-data/SOMA/blob/8a2e014beecb648de00227974c0f06e20d5da417/images/SOMAExperiment.png

**Comment by johnkerl** [comment]
@atolopko-czi I'll downsize as a follow-on PR -- thanks, good catch!! :)

**Pull request merged**
